<?php

return [
    'jquery' => 'vendor/jquery-3.6.0/dist/jquery.min.js',
    'jqueryui' => 'vendor/jquery-ui/jquery-ui.min.js',
    'bootstrap' => 'vendor/bootstrap/dist/js/bootstrap.min.js',
    'raphael' => 'vendor/raphael/raphael.min.js',
    'morris' => 'vendor/morris.js/morris.min.js',
    'sparkline' => 'vendor/jquery-sparkline/dist/jquery.sparkline.min.js',
    'knob' => 'vendor/jquery-knob/dist/jquery.knob.min.js',
    'moment' => 'vendor/moment/min/moment.min.js',
    'daterangepicker' => 'vendor/bootstrap-daterangepicker/daterangepicker.js',
    'datepicker' => 'vendor/bootstrap-datepicker/dist/js/bootstrap-datepicker.min.js',
    'slimscroll' => 'vendor/jquery-slimscroll/jquery.slimscroll.min.js',
    'fastclick' => 'vendor/fastclick/lib/fastclick.js',
    'adminlte' => 'js/adminlte.min.js',
    'common' => 'js/common.js',
    'select2' => 'vendor/select2/dist/js/select2.min.js',
    'inteltel' => 'js/intlTelInput.min.js',
    'lodash' => 'js/lodash.js',
    'sweetalert' => 'vendor/package/dist/sweetalert2.all.min.js',
    'new_jquery' => 'https://code.jquery.com/jquery-3.6.0.min.js',
    'new_select2' => 'vendor/select2-4.0.13/dist/js/select2.min.js',
    'tinymce' => 'vendor/tinymce/js/tinymce/tinymce.min.js',
    'menu-editor' => 'vendor/Menu-Editor-Vanilla-JS/dist/menu-editor.js',
    'jquery-menu-editor' => 'vendor/jQuery-Menu-Editor/jquery-menu-editor.js',
    'jquery-ui' => 'vendor/jquery-ui/jquery-ui.min.js',
    'iconpicker' => 'vendor/jQuery-Menu-Editor/bootstrap-iconpicker/js/bootstrap-iconpicker.min.js',
    'dropzone' =>'vendor/dropzone/dropzone.js',
    'morris' => 'vendor/morris.js/morris.js',
    'raphael' => 'vendor/raphael/raphael.min.js',
    // Components
    'registration' => 'js/registration.js',
    'login' => 'js/login.js',
    'indexjquery' => 'https://code.jquery.com/jquery-1.12.0.min.js',
    'indexcarousel' => 'https://cdnjs.cloudflare.com/ajax/libs/owl-carousel/1.3.3/owl.carousel.min.js',
    'indexscript' => 'js/indexscript.js',

];
